name: ricky_store
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  dropdown_search: ^5.0.3
  flutter_widget_from_html: ^0.9.0
  sp_util: ^2.0.3
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0 
  flutter_staggered_grid_view: ^0.6.2
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

